### ISSUE TITLE
Bold text is back

### ISSUE THREAD

**Issue by eldestdawn** [Fenoxo/sourceTiTS#390] opened 2015-06-03 08:58 UTC
Unable to successfully get it to repeat on the same fight but it is after combat and after you reach max exp for your current level. after a few fights the text all goes bold.

**Comment by Fenoxo** [comment] 2015-06-03 23:47
There was a bug in an older patch where completing combat would bug out and perma-bold everything. It was since fixed.

**Comment by Fenoxo** [comment] 2015-06-03 23:47
Ah, judging by the title you were aware of them. I've not come across this in any of my gameplay. Lemme know if you work out a way to reproduce it.

**Comment by eldestdawn** [comment] 2015-06-05 08:26
i should probably try testing with a clean save, since i edited my current save using the save editor to add selected body parts and enhance current ones as well as increase cash available for purchasing and stuff. after i start over i'll pay attention to when it goes bold and what caused it.

**Comment by eldestdawn** [comment] 2015-06-05 08:48
it seems to be random as to how it happens. i can't get it to repeat with the same path but i have gotten it to activate on a new game. it activated through syri's game scenes so it's not only combat that initiates it. i tried to get it to show up again doing the same thing to get to that point but it didn't reproduce. it may even just be chrome's flash player being retarded.

**Comment by Fenoxo** [comment] 2015-06-07 06:25
Fought with it some in nyrea alpha stuff: https://github.com/Fenoxo/sourceTiTS/commit/146f2b41fe6ceddd89dfb69c7d4773ef7f7b15a3

**Comment by eldestdawn** [comment] 2015-06-10 02:34
after my last comment i haven't seen it again on the new game. it may be the other save files are dirty and cause the bug to appear since they had it happen during the original bold text problem.

**Comment by Gedan** [comment] 2015-06-18 19:12
Should be fixed now.

**Closed by Gedan** 2015-06-18 19:12 UTC
