### ISSUE TITLE
Random Anno Bug

### ISSUE THREAD

**Issue by quaggaman555555** [Fenoxo/sourceTiTS#364] opened 2015-04-17 17:11 UTC
Ok, so I got this bug after selling Anno the Custom LP Pistol from the pirate ship, and the Xenogen Atma Armor Mk.1. I don't know of the other circumstances. The only other things that happened were that I had  the Royal Nectar and Blue Balls status effects. I was on Myrellion at the time. This happened right after clicking the back button to go to her main menu on the ship. Here is the scene where it happened and the error report from in-game:

You give a light rap on Anno’s door, and are quickly let in. “Hey, boss!” she says with a smile, ushering you in. 

Anno plops down on the side of her bed, arms spread back to support her... which has the added bonus of thrusting her chest out against the half-zipped front of her catsuit. “Did you need something, babe? Maybe a little stress relief?”

Something bad happened!

Please report this message, and include any prior scene text or a description of what you did before seeing this message:

Version: 0.5.31

Error: Error #1502
	at fl.managers::FocusManager/findFocusManagerComponent()
	at fl.managers::FocusManager/focusInHandler()
	at fl.core::UIComponent/setFocus()
	at fl.managers::FocusManager/activateHandler()

**Comment by Fenoxo** [comment] 2015-04-18 16:42
I can't reproduce it on my end. Can I get a copy of your save file to test with?

**Comment by Fenoxo** [comment] 2015-05-03 21:22
Closing this since I couldn't repro it and the reporter has vanished.

**Closed by Fenoxo** 2015-05-03 21:22 UTC
